volumes:
  m2:
    name: example.clj-otel.m2
    external: true
  gitlibs:
    name: example.clj-otel.gitlibs
    external: true

services:

  # Example microservice word-length-service
  word-length-service:
    image: clojure:temurin-22-tools-deps-alpine
    env_file: compose.env
    ports:
      - "8091:8091"      # nREPL server
    volumes:
      - m2:/root/.m2
      - gitlibs:/root/.gitlibs
      - ../../../../clj-otel-api:/app/clj-otel-api:ro
      - ../../../common:/app/examples/common:ro
      - ../../../opentelemetry-javaagent.jar:/app/examples/opentelemetry-javaagent.jar:ro
      - ./word-length-service/deps.edn:/app/examples/microservices/auto-instrument/middleware/word-length-service/deps.edn:ro
      - ./word-length-service/dev:/app/examples/microservices/auto-instrument/middleware/word-length-service/dev:ro
      - ./word-length-service/resources:/app/examples/microservices/auto-instrument/middleware/word-length-service/resources:ro
      - ./word-length-service/src:/app/examples/microservices/auto-instrument/middleware/word-length-service/src:ro
    working_dir: "/app/examples/microservices/auto-instrument/middleware/word-length-service"
    command: "clojure -J-XX:MaxRAMPercentage=70.0 -J-XX:+UseG1GC -M:otel:log4j:dev -m example.word-length-service.repl"
    mem_limit: 768mb
    memswap_limit: 768mb
    cpu_count: 2
    healthcheck:
      start_period: 120s
      interval: 5s
      timeout: 1s
      retries: 2
      test: "wget --spider -q http://localhost:8081/ping || exit 1"
    depends_on:
      otel-collector:
        condition: service_started


  # Example microservice sentence-summary-service
  sentence-summary-service:
    image: clojure:temurin-22-tools-deps-alpine
    env_file: compose.env
    environment:
      SERVER:
    ports:
      - "8090:8090"      # nREPL server
    volumes:
      - m2:/root/.m2
      - gitlibs:/root/.gitlibs
      - ../../../../clj-otel-api:/app/clj-otel-api:ro
      - ../../../common:/app/examples/common:ro
      - ../../../opentelemetry-javaagent.jar:/app/examples/opentelemetry-javaagent.jar:ro
      - ./sentence-summary-service/deps.edn:/app/examples/microservices/auto-instrument/middleware/sentence-summary-service/deps.edn:ro
      - ./sentence-summary-service/dev:/app/examples/microservices/auto-instrument/middleware/sentence-summary-service/dev:ro
      - ./sentence-summary-service/resources:/app/examples/microservices/auto-instrument/middleware/sentence-summary-service/resources:ro
      - ./sentence-summary-service/src:/app/examples/microservices/auto-instrument/middleware/sentence-summary-service/src:ro
    working_dir: "/app/examples/microservices/auto-instrument/middleware/sentence-summary-service"
    command: "clojure -J-XX:MaxRAMPercentage=70.0 -J-XX:+UseG1GC -M:otel:log4j:dev -m example.sentence-summary-service.repl"
    mem_limit: 768mb
    memswap_limit: 768mb
    cpu_count: 2
    healthcheck:
      start_period: 120s
      interval: 5s
      timeout: 1s
      retries: 2
      test: "wget --spider -q http://localhost:8080/ping || exit 1"
    depends_on:
      word-length-service:
        condition: service_healthy
      otel-collector:
        condition: service_started


  # Load generator for sentence-summary-service
  sentence-summary-load-gen:
    image: clojure:temurin-22-tools-deps-alpine
    env_file: compose.env
    ports:
      - "8092:8092"      # nREPL server
    volumes:
      - m2:/root/.m2
      - gitlibs:/root/.gitlibs
      - ../../../common:/app/examples/common:ro
      - ./sentence-summary-load-gen/deps.edn:/app/examples/microservices/auto-instrument/middleware/sentence-summary-load-gen/deps.edn:ro
      - ./sentence-summary-load-gen/dev:/app/examples/microservices/auto-instrument/middleware/sentence-summary-load-gen/dev:ro
      - ./sentence-summary-load-gen/resources:/app/examples/microservices/auto-instrument/middleware/sentence-summary-load-gen/resources:ro
      - ./sentence-summary-load-gen/src:/app/examples/microservices/auto-instrument/middleware/sentence-summary-load-gen/src:ro
    working_dir: "/app/examples/microservices/auto-instrument/middleware/sentence-summary-load-gen"
    command: "clojure -J-XX:MaxRAMPercentage=70.0 -M:log4j:dev -m example.sentence-summary-load-gen.repl"
    mem_limit: 768mb
    memswap_limit: 768mb
    depends_on:
      sentence-summary-service:
        condition: service_healthy


  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    environment:
      GOMEMLIMIT: "400MiB"
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    command:
      - --config=/etc/otel-collector.yaml
    mem_limit: 768mb
    memswap_limit: 768mb
    depends_on:
      tempo:
        condition: service_started
      prometheus:
        condition: service_started


  # Tempo
  tempo:
    image: grafana/tempo:2.4.1
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    command:
      - -config.file=/etc/tempo.yaml


  # Prometheus
  prometheus:
    image: prom/prometheus:v2.45.5
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage


  # Grafana
  grafana:
    image: grafana/grafana-oss:10.4.2
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
    environment:
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_NEWS_NEWS_FEED_ENABLED=false
    ports:
      - "3000:3000"       # Grafana web interface
    depends_on:
      - tempo
      - prometheus
