services:

  # Example microservice word-length-service
  word-length-service:
    image: example.clj-otel/word-length-service:latest
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_METRIC_EXPORT_INTERVAL: 10000
      OTEL_LOGS_EXPORTER: none
    depends_on:
      otel-collector:
        condition: service_started

  # Example microservice sentence-summary-service
  sentence-summary-service:
    image: example.clj-otel/sentence-summary-service:latest
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_METRIC_EXPORT_INTERVAL: 10000
      OTEL_LOGS_EXPORTER: none
      SERVER: ${SERVER}  # Select "sync", "bound-async" or "explicit-async" example server
      WORD_LENGTH_SERVICE_ENDPOINT: http://word-length-service:8081
    depends_on:
      word-length-service:
        condition: service_healthy
      otel-collector:
        condition: service_started

  # Load generator for sentence-summary-service
  sentence-summary-load-gen:
    image: example.clj-otel/sentence-summary-load-gen:latest
    environment:
      SENTENCE_SUMMARY_SERVICE_ENDPOINT: http://sentence-summary-service:8080
    depends_on:
      sentence-summary-service:
        condition: service_healthy

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    command:
      - --config=/etc/otel-collector.yaml
    depends_on:
      jaeger:
        condition: service_started
      prometheus:
        condition: service_started

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    command:
      - --collector.otlp.enabled=true
    ports:
      - "16686:16686"    # Jaeger web interface

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    ports:
      - "9090:9090"      # Prometheus web interface
