services:

  # Example microservice random-word-service
  random-word-service:
    image: example.clj-otel/random-word-service:latest
    env_file: compose.env
    ports:
      - "8091:8091"      # nREPL server
    depends_on:
      otel-collector:
        condition: service_started

  # Example microservice puzzle-service
  puzzle-service:
    image: example.clj-otel/puzzle-service:latest
    env_file: compose.env
    environment:
      SERVER: ${SERVER}  # Select "sync", "bound-async" or "explicit-async" example server
    ports:
      - "8090:8090"      # nREPL server
    depends_on:
      random-word-service:
        condition: service_healthy
      otel-collector:
        condition: service_started

  # Load generator for puzzle-service
  puzzle-load-gen:
    image: example.clj-otel/puzzle-load-gen:latest
    env_file: compose.env
    depends_on:
      puzzle-service:
        condition: service_healthy

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    command:
      - --config=/etc/otel-collector.yaml
    depends_on:
      jaeger:
        condition: service_started
      prometheus:
        condition: service_started

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    command:
      - --collector.otlp.enabled=true
    ports:
      - "16686:16686"    # Jaeger web interface

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    ports:
      - "9090:9090"      # Prometheus web interface
