version: "2"
services:

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    command:
      - --collector.otlp.enabled=true
    ports:
      - "16686:16686"  # Jaeger web interface

  # Zipkin
  zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "9411:9411"    # Zipkin endpoint and web interface

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    ports:
      - "9090:9090"    # Prometheus web interface

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command:
      - --config=/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"    # OTLP gRPC receiver
#      - "4318:4318"    # OTLP HTTP receiver
      - "13133:13133"  # health_check extension
    depends_on:
      - jaeger
      - zipkin
      - prometheus
