version: "3"
services:

  # Example microservice sum-service
  sum-service:
    image: example/sum-service:latest
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_METRIC_EXPORT_INTERVAL: 10000
      OTEL_LOGS_EXPORTER: none
    depends_on:
      otel-collector:
        condition: service_started

  # Example microservice average-service
  average-service:
    image: example/average-service:latest
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_METRIC_EXPORT_INTERVAL: 10000
      OTEL_LOGS_EXPORTER: none
      SERVER: ${SERVER}  # Select "sync", "bound-async" or "explicit-async" example server
      SUM_SERVICE_ENDPOINT: http://sum-service:8081
    depends_on:
      sum-service:
        condition: service_healthy
      otel-collector:
        condition: service_started

  # Load generator for average-service
  average-load-gen:
    image: example/average-load-gen:latest
    environment:
      AVERAGE_SERVICE_ENDPOINT: http://average-service:8080
    depends_on:
      average-service:
        condition: service_healthy

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command:
      - --config=/etc/otel-collector-config.yaml
    depends_on:
      jaeger:
        condition: service_started
      prometheus:
        condition: service_started

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    command:
      - --collector.otlp.enabled=true
    ports:
      - "16686:16686"    # Jaeger web interface

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    ports:
      - "9090:9090"      # Prometheus web interface
